version: "3"
services:
  db:
    image: postgres
    hostname: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=evefittingwarehouse
      - POSTGRES_USER=evefittingwarehouse
      - POSTGRES_DB=evefittingwarehouse
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata: