# Generated by Django 2.0.6 on 2018-06-10 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Fitting name')),
            ],
        ),
        migrations.CreateModel(
            name='Hull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Hull name')),
                ('hull_class', models.TextField()),
                ('faction', models.TextField(choices=[('amarr', 'Amarr Empire'), ('caldari', 'Caldari State'), ('gallente', 'Gallente Federation'), ('minmatar', 'Minmatar Republic'), ('angel', 'Angel Cartel'), ('blood', 'Blood Raiders'), ('guristas', 'Guristas'), ('mordu', "Mordu's Legion"), ('sansha', "Sansha's Nation"), ('serpentis', 'Serpentis'), ('sisters', 'Sisters Of EVE')])),
                ('tier', models.IntegerField()),
                ('slots_low', models.IntegerField(verbose_name='Number of low powered slots')),
                ('slots_medium', models.IntegerField(verbose_name='Number of medium powered slots')),
                ('slots_high', models.IntegerField(verbose_name='Number of high powered slots')),
                ('slots_rigs', models.IntegerField(verbose_name='Number of rig slots')),
                ('launchers', models.IntegerField(verbose_name='Max mounted launchers')),
                ('turrets', models.IntegerField(verbose_name='Max mounted turrets')),
                ('drone_capacity', models.IntegerField()),
                ('drone_bandwith', models.IntegerField()),
                ('calibration', models.IntegerField()),
                ('power', models.IntegerField(verbose_name='Powergrid')),
                ('cpu', models.IntegerField(verbose_name='CPU')),
                ('capacitor', models.IntegerField(verbose_name='Capacitor')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Module name')),
                ('slot', models.TextField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')])),
                ('required_cpu', models.IntegerField(verbose_name='CPU')),
                ('required_power', models.IntegerField(verbose_name='Powergrid')),
                ('fitting', models.ManyToManyField(to='fitting.Fitting')),
            ],
        ),
        migrations.AddField(
            model_name='fitting',
            name='hull',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitting.Hull'),
        ),
    ]
