# Generated by Django 2.0.6 on 2018-07-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0002_auto_20180610_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('C', 'Capital')])),
                ('calibration', models.IntegerField(verbose_name='Calibration cost')),
                ('drawback', models.IntegerField(verbose_name='Drawback [%]')),
            ],
        ),
        migrations.AlterField(
            model_name='hull',
            name='hull_class',
            field=models.TextField(choices=[('shuttle', 'Shuttle'), ('corvette', 'Corvette'), ('frigate', 'Frigate'), ('cruiser', 'Cruiser'), ('bcruiser', 'Battlecruiser'), ('bship', 'Battleship'), ('capital', 'Capital')]),
        ),
    ]
