# Generated by Django 2.0.6 on 2018-08-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0003_auto_20180721_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='fitting',
        ),
    ]
