# Generated by Django 2.0.6 on 2018-08-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0004_remove_module_fitting'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='tier',
            field=models.TextField(choices=[('1', 'I'), ('2', 'II'), ('1.1', 'Meta 1'), ('1.2', 'Meta 2'), ('1.3', 'Meta 3'), ('1.4', 'Meta 4'), ('story', 'Storyline'), ('faction', 'Faction'), ('deadspace', 'Deadspace'), ('officer', 'Officer')], default=1),
            preserve_default=False,
        ),
    ]
