# Generated by Django 2.0.6 on 2018-08-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0006_auto_20180817_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='activation_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
