# Generated by Django 2.0.6 on 2018-08-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0007_auto_20180817_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hull',
            name='faction',
            field=models.TextField(choices=[('amarr', 'Amarr Empire'), ('caldari', 'Caldari State'), ('gallente', 'Gallente Federation'), ('minmatar', 'Minmatar Republic'), ('angel', 'Angel Cartel'), ('blood', 'Blood Raiders'), ('guristas', 'Guristas'), ('mordu', "Mordu's Legion"), ('sansha', "Sansha's Nation"), ('serpentis', 'Serpentis'), ('sisters', 'Sisters Of EVE'), ('triglavian', 'Triglavian Collective')]),
        ),
        migrations.AlterField(
            model_name='module',
            name='activation_cost',
            field=models.IntegerField(default=0, verbose_name='Activation cost [GJ]'),
        ),
        migrations.AlterField(
            model_name='module',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration [s]'),
        ),
        migrations.AlterField(
            model_name='module',
            name='slot',
            field=models.TextField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')]),
        ),
    ]
