# Generated by Django 2.0.6 on 2018-08-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0008_auto_20180817_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='name',
            field=models.TextField(default='', verbose_name='Rig name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hull',
            name='capacitor',
            field=models.IntegerField(verbose_name='Capacitor [GJ]'),
        ),
        migrations.AlterField(
            model_name='hull',
            name='cpu',
            field=models.IntegerField(verbose_name='CPU [tf]'),
        ),
        migrations.AlterField(
            model_name='hull',
            name='power',
            field=models.IntegerField(verbose_name='Powergrid [MW]'),
        ),
        migrations.AlterField(
            model_name='module',
            name='required_cpu',
            field=models.IntegerField(verbose_name='CPU [tf]'),
        ),
        migrations.AlterField(
            model_name='module',
            name='required_power',
            field=models.IntegerField(verbose_name='Powergrid [MW]'),
        ),
    ]
